### ISSUE TITLE
The given account is not owned by the executing program

### ISSUE THREAD

**Issue by antoniomuso** [saxenism/solana-calculator#2]
I have this problem when I run the tests: 
```
 Creates a calculator:
     Error: 3007: The given account is not owned by the executing program
      at Function.parse (node_modules/@project-serum/anchor/src/error.ts:41:14)
      at Object.rpc [as create] (node_modules/@project-serum/anchor/src/program/namespace/rpc.ts:32:42)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
the test that fails is:
```ts
describe("mycalculatordapp", () => {
  const provider = anchor.Provider.local();
  anchor.setProvider(provider);
  let _calculator;

  const calculator = anchor.web3.Keypair.generate();

  const program = anchor.workspace.Mycalculatordapp;

  it("Creates a calculator", async () => {
    await program.rpc.create("Welcome to Solana", {
      accounts: {
        calculator: calculator.publicKey,
        user: provider.wallet.publicKey,
        systemProgram: SystemProgram.programId,
      },
      signers: [calculator],
    });

    const account = await program.account.calculator.fetch(
      calculator.publicKey
    );
    assert.ok(account.greeting === "Welcome to Solana");
    _calculator = calculator;
  });
```

**Comment by antoniomuso** [comment]
I solved it. The issue was the names that were differents.

**Comment by adityabharadwaj198** [comment]
Hey @antoniomuso , how exactly did you fix this? Which names were different?
